### PR TITLE
BFCP: fix check on payload length and extract metadata

### LINKED ISSUE #2745: BFCP pcap
@0xA50C1A1, is it possible that the file `tests/cfgs/default/pcap/bfcp.pcapng` contains malformed/invalid packets? May it be some kind of "artificial/handmade" traffic?

I am trying to improve BFCP detection and this traffic looks invalid to me....

### PR DESCRIPTION
**Pull request by IvanNardi**
We should be able to identified this protocol on the first packet, without keeping any state

Close #2745

### CODE REVIEW

**Comment by IvanNardi** [comment]
@0xA50C1A1, could you take a look, please?

**Comment by 0xA50C1A1** [comment]
> @0xA50C1A1, could you take a look, please?

Perfect. What do you think about extracting the user ID and conference ID as metadata, could that be useful?

File: src/lib/protocols/bfcp.c [hunk 1]
```diff
@@ -45,7 +45,13 @@ static void ndpi_search_bfcp(struct ndpi_detection_module_struct *ndpi_struct,
   u_int8_t version = (packet->payload[0] >> 5) & 0x07;
   u_int8_t reserved = (packet->payload[0] >> 3) & 0x01;
```
Comment (0xA50C1A1) [inline src/lib/protocols/bfcp.c]: Should we check reserved bits?

**Comment by IvanNardi** [comment]
> > @0xA50C1A1, could you take a look, please?
> 
> Perfect. What do you think about extracting the user ID and conference ID as metadata, could that be useful?

I don't know, but it would be trivial to do. I'll push a new version

File: src/lib/protocols/bfcp.c (hunk 1 above)
Comment (IvanNardi) [reply src/lib/protocols/bfcp.c]: I think so, but this check is wrong; we should check last 3 bits...
