### PR TITLE
fuzz: harden ndpi_hex_decode and add targeted parser harnesses

### LINKED ISSUE #3159: [Fuzzing] Heap OOB read: ndpi_hex_decode sscanf on non-NUL-terminated buffer (via ndpi_decode_tls_blocks)
## Summary

Fuzzing the public `NDPI_EXPORT` API `ndpi_decode_tls_blocks` uncovered a heap out-of-bounds **read** in `ndpi_hex_decode` (`src/lib/ndpi_utils.c:1144`). The per-byte `sscanf("%02hhX", …)` loop does not require its input to be NUL-terminated, but glibc's `sscanf` internally calls `memchr(s, 0, SIZE_MAX)` via `_IO_str_init_static_internal` to compute the string length — so it walks past the end of the caller's buffer. Under ASAN this lands in the heap redzone and the process crashes.

- **Severity:** High (DoS; mild info-disclosure potential)
- **Type:** Memory safety — heap out-of-bounds read
- **Affected function:** `ndpi_hex_decode` at `src/lib/ndpi_utils.c:1144`, reachable from the public `NDPI_EXPORT` API `ndpi_decode_tls_blocks` at `src/lib/ndpi_utils.c:5344`
- **Commit tested:** `ea3586e663ae53f26f159412f48d519d52ae623d` (branch `dev`)
- **Discovered by:** a new libFuzzer harness `fuzz_ndpi_decode_tls_blocks` (ASAN+UBSAN), ~311 M execs, 211 crash artifacts deduplicated to this single root cause.

In-tree callers in `src/lib/protocols/tls.c` happen to pass NUL-terminated strings, so the in-tree dissectors do not trip the bug. The risk is to out-of-tree consumers that feed untrusted bytes to the public API — the NUL-termination precondition is undocumented.

## Root cause

`src/lib/ndpi_utils.c:1144`:

```c
for (i = 0; i < *out_len; i++) {
  sscanf((const char*)&src[ret_idx], "%02hhX", &ret[i]);
  ret_idx += 2;
}
```

`src` is the caller-supplied buffer and is not NUL-terminated. glibc wraps `src` in an `_IO_strfile` whose initializer (`_IO_str_init_static_internal`, `libio/strops.c:41`) calls `memchr(s, 0, SIZE_MAX)` to compute the string length. Without a terminator the walk continues past the end of the `ndpi_malloc(len/2 + 1)` allocation. Every one of 211 crash inputs produces the same top-5 ASAN stack:

```
AddressSanitizer: SEGV on unknown address 0x5NN000NN0000 (READ)
  #0 memchr-evex.S:246
  #1 _IO_str_init_static_internal       libio/strops.c:41
  #2 __vsscanf_internal                 libio/strfile.h:95
  #3 __isoc99_sscanf
  #4 ndpi_hex_decode                    src/lib/ndpi_utils.c:1144
  #5 ndpi_decode_tls_blocks             src/lib/ndpi_utils.c:5344
```

The fault addresses (`0x504000…/0x506000…/0x508000…/0x50c000…/0x510000…`) are ASAN's heap-redzone shadow region, consistent with a read past the end of the `ndpi_malloc`'d buffer.

Note: commit `a07d5500` ("fuzz: try to improve fuzzing coverage", 2025-10-06) touched this loop to change `%X` → `%02hhX` — fixing a write-width bug but not this read-side NUL-termination precondition.

## Exploitability

OOB read only — no OOB write, no user-controlled data crosses an indirect branch. Direct RCE is not plausible. Realistic impact:

1. Process crash / DoS in any host application that feeds untrusted bytes to `ndpi_decode_tls_blocks`.
2. Weak side-channel info disclosure through the `memchr` walk length (timing).

## Reproduction

Minimal crash input (48 bytes), `fuzz/crashes/fuzz_ndpi_decode_tls_blocks/crash-02b3105c0abb454df309d9c3fe448026765e88ef`:

```
00000000: ebeb ebeb ebeb ebeb ebeb ebeb ebeb ebeb  ................
00000010: ebeb ebeb ebeb ebeb ebeb ebeb ebef ebeb  ................
00000020: ebeb ebeb ebeb ebeb ebeb ebeb ebeb 6162  ..............ab
```

Single-input replay is **unreliable** — whether `memchr` crosses a redzone depends on the surrounding allocator state, so a fresh process on a single input often does not SEGV. Fork-mode replay against the corpus reproduces reliably:

```sh
# Build (from project root):
./autogen.sh && ./configure --enable-fuzztargets \
  CC=clang CXX=clang++ \
  CFLAGS='-fsanitize=fuzzer-no-link,address,undefined -g -O1' \
  CXXFLAGS='-fsanitize=fuzzer-no-link,address,undefined -g -O1' \
  LIB_FUZZING_ENGINE='-fsanitize=fuzzer'
make -C fuzz fuzz_ndpi_decode_tls_blocks

# Reproduce (27 crashes in ~21 s on a corpus of ~200 inputs):
./fuzz/fuzz_ndpi_decode_tls_blocks -fork=2 -ignore_crashes=1 \
    -max_total_time=20 fuzz/corpus/fuzz_ndpi_decode_tls_blocks/
```

The harness is a one-shot: it takes the fuzzer-supplied buffer and calls `ndpi_decode_tls_blocks(buf, len, out, &out_len)` with no other setup. Any non-NUL-terminated even-length buffer ≥ 2 B whose tail happens to fall adjacent to an ASAN redzone will crash.

## Suggested fix

**Preferred** — replace the per-byte `sscanf` with a bounded hex-nibble table. Correct regardless of NUL-termination and ~100× faster:

```c
static inline int hexval(u_char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return 10 + (c - 'a');
  if (c >= 'A' && c <= 'F') return 10 + (c - 'A');
  return -1;
}

/* in the loop, after bounds-checking ret_idx + 1 against src_len: */
int hi = hexval(src[ret_idx]), lo = hexval(src[ret_idx + 1]);
if (hi < 0 || lo < 0) { /* bail */ }
ret[i] = (u_char)((hi << 4) | lo);
```

**Fallback** — copy `encoded_blocks` into a NUL-terminated scratch buffer inside `ndpi_decode_tls_blocks` before handing it to `ndpi_hex_decode`, and document the precondition on the public API. The table rewrite is preferred because it also covers any future caller of `ndpi_hex_decode`.

Happy to submit a PR with the table-based decoder if useful.

### PR DESCRIPTION
**Pull request by parasol-aser**
## Summary

Closes #3159.

This follows the issue thread's requested fix direction: `ndpi_hex_decode()` now uses a bounded nibble decoder instead of relying on `sscanf()` over a borrowed buffer, rather than papering over `ndpi_decode_tls_blocks()` with a scratch NUL-terminated copy. It also upstreams the direct `fuzz_ndpi_decode_tls_blocks` reproducer that Ivan Nardi asked about in the follow-up comment, plus three additional focused parser fuzz targets from the same fuzzing pass.

## Changes

- replace the per-byte `sscanf("%02hhX", ...)` loop with a bounded hex decoder that accepts explicit-length, non-NUL-terminated buffers, rejects odd-length or malformed hex, and zeros `out_len` on failure
- harden `ndpi_decode_tls_blocks()` to zero `num_tls_blocks` on entry and fail closed on malformed decode results instead of partially parsing truncated data
- document the explicit-length semantics and failure behavior for `ndpi_hex_decode()` and `ndpi_decode_tls_blocks()` in `ndpi_api.h`
- add unit coverage for non-NUL-terminated, mixed-case, invalid, and odd-length hex input plus TLS-block round-trips and malformed payload handling
- add `fuzz_ndpi_decode_tls_blocks` and wire it into `fuzz/Makefile.am`
- add focused `fuzz_dns_parse`, `fuzz_http_parse`, and `fuzz_tls_client_server_hello` harnesses and register them in `fuzz/Makefile.am`

## Test Plan

- `make -j4 -C fuzz fuzz_ndpi_decode_tls_blocks fuzz_dns_parse fuzz_http_parse fuzz_tls_client_server_hello`
- `./fuzz/fuzz_ndpi_decode_tls_blocks -fork=2 -ignore_crashes=1 -max_total_time=20 fuzz/corpus/fuzz_ndpi_decode_tls_blocks/`
- smoke-start `fuzz_dns_parse`, `fuzz_http_parse`, and `fuzz_tls_client_server_hello` with `-runs=0` after staging the expected sidecar data files next to the binaries
- attempted `make -j4 -C tests/unit`, but this environment is missing the `json.h` / json-c headers needed to build `tests/unit/unit`

### CODE REVIEW

**Comment by IvanNardi** [comment]
@parasol-aser, could you sign the CLA, please?

**Comment by parasol-aser** [comment]
> @parasol-aser, could you sign the CLA, please?

is there a link?

**Comment by IvanNardi** [comment]
> > @parasol-aser, could you sign the CLA, please?
> 
> is there a link?

https://docs.google.com/forms/d/e/1FAIpQLScbtEQSqv88HGN1YFENxiIQoRqvFh_5NL9pqwmJjZmU-wMbSA/viewform
from:
https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md

**Comment by parasol-aser** [comment]
@IvanNardi done

**Comment by IvanNardi** [comment]
As a first step, I rebased your code to add a fix

File: fuzz/fuzz_dns_parse.c [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+    memcpy(&pkt[IPV4_HDR_LEN + 2], &dport, 2);
+  }
+  udp_len = htons((uint16_t)(UDP_HDR_LEN + payload_len));
+  memcpy(&pkt[IPV4_HDR_LEN + 4], &udp_len, 2);
+
+  if (payload_len > 0)
+    memcpy(&pkt[IPV4_HDR_LEN + UDP_HDR_LEN], data, payload_len);
+
+  memset(&flow, 0, SIZEOF_FLOW_STRUCT);
+  ndpi_detection_process_packet(ndpi_info_mod, &flow, pkt,
```
Comment (IvanNardi) [inline fuzz/fuzz_dns_parse.c]: I am not sure this is the right function to call... can it be more effective if we directly call `ndpi_search_dns`, with a proper fake `flow` structure?
Similar to `fuzz_quic_get_crypto_data.c` or `fuzz_is_stun.c`....

File: fuzz/fuzz_http_parse.c [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+    memcpy(&pkt[IPV4_HDR_LEN + 2], &dport, 2);
+  }
+  pkt[IPV4_HDR_LEN + 12] = 0x50;   /* data offset = 5 */
+  pkt[IPV4_HDR_LEN + 13] = 0x18;   /* flags = PSH | ACK */
+
+  if (payload_len > 0)
+    memcpy(&pkt[IPV4_HDR_LEN + TCP_HDR_LEN], data, payload_len);
+
+  memset(&flow, 0, SIZEOF_FLOW_STRUCT);
+  ndpi_detection_process_packet(ndpi_info_mod, &flow, pkt,
```
Comment (IvanNardi) [inline fuzz/fuzz_http_parse.c]: Same as above, but `ndpi_search_http_tcp`

File: tests/unit/unit.c [hunk 3]
```diff
@@ -61,6 +61,54 @@ static int verbose = 0;
...
+    if(encoded[i] >= 'a' && encoded[i] <= 'f') {
+      if((i & 0x1) == 0)
+	encoded[i] -= 'a' - 'A';
+    } else if(encoded[i] >= 'A' && encoded[i] <= 'F') {
+      if((i & 0x1) == 1)
+	encoded[i] += 'a' - 'A';
+    }
+  }
+}
+
```
Comment (IvanNardi) [inline tests/unit/unit.c]: Please move these unit tests to example/utests.c with the same logic

File: tests/unit/unit.c [hunk 4]
```diff
@@ -262,6 +310,114 @@ int serializerUnitTest() {
...
+  assert(ndpi_decode_tls_blocks((const u_char *)"", 0, &num_blocks) == NULL);
+  assert(num_blocks == 0);
+
+  printf("%30s                      OK\n", __func__);
+
+  return 0;
+}
+
+/* *********************************************** */
+
```
Comment (IvanNardi) [inline tests/unit/unit.c]: Same

**Review by IvanNardi — CHANGES_REQUESTED** [review]
I have some doubts about the dns and http fuzzers.
The rest seems right.
@parasol-aser, what do you think?

File: fuzz/fuzz_dns_parse.c (hunk 1 above)
Comment (parasol-aser) [reply fuzz/fuzz_dns_parse.c]: Replaced the IP/UDP-wrapping approach with a direct call to ndpi_search_dns() using a synthesised packet_struct (mirrors fuzz_is_stun / fuzz_quic_get_crypto_data). ndpi_search_dns is now exposed via ndpi_private.h. Selector byte also flips TCP/UDP and DNS/MDNS ports.

File: fuzz/fuzz_http_parse.c (hunk 2 above)
Comment (parasol-aser) [reply fuzz/fuzz_http_parse.c]: Same treatment: fuzz_http_parse now calls ndpi_search_http_tcp() directly with a synthesised packet_struct. ndpi_search_http_tcp is exposed via ndpi_private.h.

File: tests/unit/unit.c (hunk 3 above)
Comment (parasol-aser) [reply tests/unit/unit.c]: Moved checkHexDecode / checkTlsBlocksDecode / rewriteHexCase helpers to example/utests.c (same logic, static).

File: tests/unit/unit.c (hunk 4 above)
Comment (parasol-aser) [reply tests/unit/unit.c]: Moved hexDecodeUnitTest and tlsBlocksUnitTest to example/utests.c and registered them in run_unit_tests(); removed from tests/unit/unit.c.

**Comment by parasol-aser** [comment]
Pushed 0843f93ce addressing the review:

- `fuzz_dns_parse` / `fuzz_http_parse` now call `ndpi_search_dns` / `ndpi_search_http_tcp` directly with a synthesised `packet_struct` (mirrors `fuzz_is_stun` / `fuzz_quic_get_crypto_data`). Both parsers are exposed via `ndpi_private.h`; `-DNDPI_LIB_COMPILATION` wired in `fuzz/Makefile.am`.
- Hex-decode and TLS-blocks unit tests (plus the `checkHexDecode` / `checkTlsBlocksDecode` / `rewriteHexCase` helpers) moved from `tests/unit/unit.c` to `example/utests.c` and registered in `run_unit_tests()`.

Built + smoke-ran both fuzzers locally (`-runs=1` and short `-max_total_time`) and ran `ndpiReader --run-tests`; no crashes or assertion failures.

**Review by IvanNardi — APPROVED** [review]
Thank you very much, for the fix and for all the follow-ups

**Comment by IvanNardi** [comment]
@parasol-aser, great work

**Comment by parasol-aser** [comment]
@IvanNardi happy to contribute, and thank you for your work!
