### PR TITLE
Fix writes to `flow->protos` union fields

### LINKED ISSUE #1342: Kerberos: wrong logic accessing flow->protos.kerberos fields
Fuzzing #1330 we found a serious bug in the Kerberos code.
The Kerberos dissector logic is something like:
* we found a Kerberos request -> we set `flow->protos.kerberos.domain` and similar metadata.
* the flow is not classified as kerberos yet; we do that only after we process the reply.
* if we don't see the reply at all or if, for whatever reasons, the final classification of the flow is not kerberos, when we free `struct ndpi_flow_struct` we end up reading/freeing  the wrong fields of the union.

Bottom line: we write to the **union** `flow->protos` using one protocol, and we free it using another one --> crash

The core issue is that we can't write to `flow->protos` until we have a final protocol.

I see two possible solutions:
1) Move kerberos fields out of `union protos`: trivial, but `struct ndpi_flow_struct` will be larger and I'd prefer to avoid doing that.
2) Update kerberos code to write to `flow->protos.kerberos.XXX` only after it set the final protocol via `ndpi_int_kerberos_add_connection()`

If no one has a better solution or some suggestions, I'll work on 2)

Note that this bug is not specific to #1330. You can trigger it with a slightly modified version of current master, too (shuffling around fields of `flow->protos.tls_quic_stun.tls_quic`)

[kerberos_fuzz.zip](https://github.com/ntop/nDPI/files/7337947/kerberos_fuzz.zip)

```
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ git diff
diff --git a/src/include/ndpi_typedefs.h b/src/include/ndpi_typedefs.h
index c3dc63e3..d3b84c74 100644
--- a/src/include/ndpi_typedefs.h
+++ b/src/include/ndpi_typedefs.h
@@ -1280,7 +1280,7 @@ struct ndpi_flow_struct {
       struct {
         char ssl_version_str[12];
        u_int16_t ssl_version, server_names_len;
-       char client_requested_server_name[256], /* SNI hostname length: RFC 4366 */
+       char
          *server_names, *alpn, *tls_supported_versions, *issuerDN, *subjectDN;
        u_int32_t notBefore, notAfter;
        char ja3_client[33], ja3_server[33];
@@ -1301,6 +1301,7 @@ struct ndpi_flow_struct {
          char *esni;
        } encrypted_sni;
        ndpi_cipher_weakness server_unsafe_cipher;
+       char client_requested_server_name[256]; /* SNI hostname length: RFC 4366 */
       } tls_quic;

       struct {
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ ./example/ndpiReader -t -i ~/kerberos_fuzz.pcapng -q
AddressSanitizer:DEADLYSIGNAL
=================================================================
==43585==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x7f999fb64b56 bp 0x6163f3f3f3693172 sp 0x7ffd80fdf1b0 T0)
==43585==The signal is caused by a READ memory access.
==43585==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x7f999fb64b56 in bool __sanitizer::atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>(__sanitizer::atomic_uint8_t volatile*, __sanitizer::atomic_uint8_t::Type*, __sanitizer::atomic_uint8_t::Type, __sanitizer::memory_order) ../../../../src/libsanitizer/sanitizer_common/sanitizer_atomic_clang.h:80
    #1 0x7f999fb64b56 in __asan::Allocator::AtomicallySetQuarantineFlagIfAllocated(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) ../../../../src/libsanitizer/asan/asan_allocator.cpp:621
    #2 0x7f999fb64b56 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) ../../../../src/libsanitizer/asan/asan_allocator.cpp:697
    #3 0x7f999fb64b56 in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) ../../../../src/libsanitizer/asan/asan_allocator.cpp:971
    #4 0x7f999fbf08b4 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:128
    #5 0x5611cadfabb8 in free_wrapper /home/ivan/svnrepos/nDPI/example/reader_util.c:329
    #6 0x5611caf50f32 in ndpi_free /home/ivan/svnrepos/nDPI/src/lib/ndpi_main.c:160
    #7 0x5611caf78810 in ndpi_free_flow_data /home/ivan/svnrepos/nDPI/src/lib/ndpi_main.c:4318
    #8 0x5611cafad4ca in ndpi_free_flow /home/ivan/svnrepos/nDPI/src/lib/ndpi_main.c:7066
    #9 0x5611caf50f84 in ndpi_flow_free /home/ivan/svnrepos/nDPI/src/lib/ndpi_main.c:173
    #10 0x5611cadfa7b3 in ndpi_free_flow_info_half /home/ivan/svnrepos/nDPI/example/reader_util.c:302
    #11 0x5611cadfc9e0 in ndpi_flow_info_free_data /home/ivan/svnrepos/nDPI/example/reader_util.c:497
    #12 0x5611cadfbd7c in ndpi_flow_info_freer /home/ivan/svnrepos/nDPI/example/reader_util.c:442
    #13 0x5611cae48e95 in ndpi_tdestroy_recurse /home/ivan/svnrepos/nDPI/src/lib/ndpi_utils.c:226
    #14 0x5611cae48eda in ndpi_tdestroy /home/ivan/svnrepos/nDPI/src/lib/ndpi_utils.c:235
    #15 0x5611cadfcb78 in ndpi_workflow_free /home/ivan/svnrepos/nDPI/example/reader_util.c:515
    #16 0x5611cad5f4a9 in terminateDetection /home/ivan/svnrepos/nDPI/example/ndpiReader.c:2175
    #17 0x5611cadd4c54 in test_lib /home/ivan/svnrepos/nDPI/example/ndpiReader.c:3616
    #18 0x5611cadde46a in main /home/ivan/svnrepos/nDPI/example/ndpiReader.c:4506
    #19 0x7f999ec9d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #20 0x5611cad1352d in _start (/home/ivan/svnrepos/nDPI/example/ndpiReader+0x89a52d)

```

### LINKED ISSUE #1343: DHCP: wrong access to `flow->protos.dhcp`
Same issue as #1342, but about DHCP protocol: we can't write to `flow->protos.dhcp` without a final classification.

Reproducible on master, with a minimal modification

[dhcp_fuzz.zip](https://github.com/ntop/nDPI/files/7339229/dhcp_fuzz.zip)

```
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ git diff
diff --git a/src/include/ndpi_typedefs.h b/src/include/ndpi_typedefs.h
index c3dc63e3..d3b84c74 100644
--- a/src/include/ndpi_typedefs.h
+++ b/src/include/ndpi_typedefs.h
@@ -1280,7 +1280,7 @@ struct ndpi_flow_struct {
       struct {
         char ssl_version_str[12];
        u_int16_t ssl_version, server_names_len;
-       char client_requested_server_name[256], /* SNI hostname length: RFC 4366 */
+       char
          *server_names, *alpn, *tls_supported_versions, *issuerDN, *subjectDN;
        u_int32_t notBefore, notAfter;
        char ja3_client[33], ja3_server[33];
@@ -1301,6 +1301,7 @@ struct ndpi_flow_struct {
          char *esni;
        } encrypted_sni;
        ndpi_cipher_weakness server_unsafe_cipher;
+       char client_requested_server_name[256]; /* SNI hostname length: RFC 4366 */
       } tls_quic;
 
       struct {
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ ./example/ndpiReader -t -i ~/dhcp-fuzz.pcapng -d -q
AddressSanitizer:DEADLYSIGNAL
=================================================================
==105281==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x7ffb07ba9675 bp 0x7ffe32f47500 sp 0x7ffe32f46c88 T0)
==105281==The signal is caused by a READ memory access.
==105281==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x7ffb07ba9675  (/lib/x86_64-linux-gnu/libc.so.6+0x18b675)
    #1 0x7ffb0893f91e in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:450
    #2 0x555bef3b8ba2 in process_ndpi_collected_info /home/ivan/svnrepos/nDPI/example/reader_util.c:1176
    #3 0x555bef2d1008 in node_proto_guess_walker /home/ivan/svnrepos/nDPI/example/ndpiReader.c:1616
    #4 0x555bef3f5785 in ndpi_trecurse /home/ivan/svnrepos/nDPI/src/lib/ndpi_utils.c:171
    #5 0x555bef3f5a18 in ndpi_twalk /home/ivan/svnrepos/nDPI/src/lib/ndpi_utils.c:191
    #6 0x555bef3715fa in printResults /home/ivan/svnrepos/nDPI/example/ndpiReader.c:2931
    #7 0x555bef3818de in test_lib /home/ivan/svnrepos/nDPI/example/ndpiReader.c:3610
    #8 0x555bef38b46a in main /home/ivan/svnrepos/nDPI/example/ndpiReader.c:4506
    #9 0x7ffb07a450b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #10 0x555bef2c052d in _start (/home/ivan/svnrepos/nDPI/example/ndpiReader+0x89a52d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x18b675) 
==105281==ABORTING

### PR DESCRIPTION
**Pull request by IvanNardi**
We can write to `flow->protos` only after a proper classification.

This issue has been found in Kerberos, DHCP, HTTP, STUN, IMO, FTP,
SMTP, IMAP and POP code.
There are two kinds of fixes:
* write to `flow->protos` only if a final protocol has been detected
* move protocol state out of `flow->protos`

The hard part is to find, for each protocol, the right tradeoff between
memory usage and code complexity.

Handle Kerberos like DNS: if we find a request, we set the protocol
and an extra callback to further parsing the reply.

For all the other protocols, move the state out of `flow->protos`. This
is an issue only for the FTP/MAIL stuff.

Add DHCP Class Identification value to the output of ndpiReader and to
the Jason serialization.

Extend code coverage of fuzz tests.

Close #1343
Close #1342

### CODE REVIEW

File: src/include/ndpi_typedefs.h [hunk 1]
```diff
@@ -1290,7 +1290,14 @@ struct ndpi_flow_struct {
...
 	u_int16_t ssl_version, server_names_len;
-	char client_requested_server_name[256], /* SNI hostname length: RFC 4366 */
+	/*
+	 *
+	 * TODO
+	 *
+	 * discard change before merge!!!
+	 *
+	 */
+	char
```
Comment (IvanNardi) [inline src/include/ndpi_typedefs.h]: Let see if oss-fuzz is able to find other similar bugs... To be reverted before the merge

Comment (IvanNardi) [reply src/include/ndpi_typedefs.h]: And that opened the Pandora's box...

**Comment by utoni** [comment]
dhcp options parsing looks good even it took some time to search for possible access-out-of-bounds issues, need to upgrade my brain

File: .github/workflows/build.yml [hunk 2]
```diff
@@ -273,12 +273,12 @@ jobs:
...
           args: >
             bash -c
+            #./tests/do.sh disabled because we know we have some problems with big-endian machines
             "apt-get -y update &&
             apt-get -y install git autoconf automake libtool pkg-config gettext libjson-c-dev flex bison libpcap-dev libgcrypt20-dev libpcre3-dev libmaxminddb-dev &&
             env CC=gcc CFLAGS='-Werror' ./autogen.sh --enable-debug-messages ${{ matrix.gcrypt }} ${{ matrix.msan }} ${{ matrix.pcre }} ${{ matrix.maxminddb }} &&
             make all &&
             make -C example ndpiSimpleIntegration &&
             make -C python &&
-            ./tests/do.sh &&
```
Comment (IvanNardi) [inline .github/workflows/build.yml]: @aouinizied, what do you think?
I prefer to have the CI pass if there are no other errors. Otherwise it is too easy to overlook CI results because "they always fail..."
We can always re-enable them when we work on that issue

Comment (aouinizied) [reply .github/workflows/build.yml]: @IvanNardi Yes, definitively. We will reactivate it later.

Comment (IvanNardi) [reply .github/workflows/build.yml]: Thanks!

Comment (IvanNardi) [reply .github/workflows/build.yml]: This change has been already merged via a dedicated PR
