### PR TITLE
Fix some invalid memory reads

### LINKED ISSUE #1348: Commit b1a43cbc introduce some memory errors
## Describe the bug

Commit b1a43cbc broke unit tests, because of multiple memory errors
The key reason is that from 730c2360 is not more valid to access `ndpi_detection_module_struct->packet` from `ndpi_detection_giveup()`
Commit b1a43cbc add a call to `ndpi_reconcile_protocols()` from `ndpi_detection_giveup()`. Therefore  `ndpi_reconcile_protocols()` (and all the functions it calls) must not access packet information

## nDPI Environment (please complete the following information):
* OS name: Ubuntu
* OS version: 20.04
* Architecture: x86_64
* nDPI version or commit hash: b97dc6ba; anything from b1a43cbc
* nDPI compilation flags used: default

### Reproducible using ndpiReader?
- [x] The reported bug is reproducible using ndpiReader.

### Steps to reproduce the behavior:

Run the unit test
```
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(dev)$ ./tests/do.sh
1kxun.pcap                                      	OK
443-chrome.pcap                                 	OK
443-curl.pcap                                   	OK
443-firefox.pcap                                	OK
443-git.pcap                                    	OK
443-opvn.pcap                                   	OK
443-safari.pcap                                 	OK
4in4tunnel.pcap                                 	OK
4in6tunnel.pcap                                 	OK
6in4tunnel.pcap                                 	OK
6in6tunnel.pcap                                 	OK
aimini-http.pcap                                	OK
ajp.pcap                                        	OK
alexa-app.pcapng                                	OK
among_us.pcap                                   	OK
amqp.pcap                                       	OK
android.pcap                                    	OK
anyconnect-vpn.pcap                             	OK
anydesk-2.pcap                                  	OK
=================================================================
==133079==ERROR: AddressSanitizer: heap-use-after-free on address 0x6060004f87ba at pc 0x0000006a8b0b bp 0x7ffe2fc16bb0 sp 0x7ffe2fc16ba8
READ of size 4 at 0x6060004f87ba thread T0
    #0 0x6a8b0a in ndpi_handle_risk_exceptions /home/ivan/svnrepos/nDPI/src/lib/ndpi_utils.c:2118:33
    #1 0x6a7f1a in ndpi_set_risk /home/ivan/svnrepos/nDPI/src/lib/ndpi_utils.c:2139:3
    #2 0x7ae36e in ndpi_reconcile_protocols /home/ivan/svnrepos/nDPI/src/lib/ndpi_main.c:4847:7
    #3 0x7aa351 in ndpi_detection_giveup /home/ivan/svnrepos/nDPI/src/lib/ndpi_main.c:5006:5
    #4 0x511f9d in node_proto_guess_walker /home/ivan/svnrepos/nDPI/example/ndpiReader.c:1610:33
    #5 0x692d67 in ndpi_trecurse /home/ivan/svnrepos/nDPI/src/lib/ndpi_utils.c:171:5
    #6 0x692c44 in ndpi_twalk /home/ivan/svnrepos/nDPI/src/lib/ndpi_utils.c:191:5
    #7 0x4f8221 in printResults /home/ivan/svnrepos/nDPI/example/ndpiReader.c:2931:7
    #8 0x4f5559 in test_lib /home/ivan/svnrepos/nDPI/example/ndpiReader.c:3610:3
    #9 0x509df3 in main /home/ivan/svnrepos/nDPI/example/ndpiReader.c:4510:7
    #10 0x7f1fe0b710b2 in __libc_start_main /build/glibc-YbNSs7/glibc-2.31/csu/../csu/libc-start.c:308:16
    #11 0x41d6ad in _start (/home/ivan/svnrepos/nDPI/example/ndpiReader+0x41d6ad)

0x6060004f87ba is located 26 bytes inside of 54-byte region [0x6060004f87a0,0x6060004f87d6)
freed by thread T1 here:
    #0 0x499bf2 in free (/home/ivan/svnrepos/nDPI/example/ndpiReader+0x499bf2)
    #1 0x629154 in free_wrapper /home/ivan/svnrepos/nDPI/example/reader_util.c:329:3
    #2 0x7683b1 in ndpi_free /home/ivan/svnrepos/nDPI/src/lib/ndpi_main.c:160:7
    #3 0x510f2c in ndpi_process_packet /home/ivan/svnrepos/nDPI/example/ndpiReader.c:3449:5
    #4 0x7f1fe10a2466  (/lib/x86_64-linux-gnu/libpcap.so.0.8+0x23466)
```

### PR DESCRIPTION
**Pull request by IvanNardi**
`ndpi_detection_giveup()` (and any functions called by it) can't access
`ndpi_detection_module_struct->packet` anymore since 730c236.

Sync unit tests results

Close #1348

### CODE REVIEW

File: src/lib/ndpi_main.c [hunk 1]
```diff
@@ -4497,6 +4497,13 @@ void ndpi_connection_tracking(struct ndpi_detection_module_struct *ndpi_str,
 	packet->packet_direction = 1;
     }
 
+    flow->is_ipv6 = !!packet->iphv6;
```
Comment (utoni) [inline src/lib/ndpi_main.c]: What about:

```suggestion
    flow->is_ipv6 = (packet->iphv6 != NULL);
```

Comment (IvanNardi) [reply src/lib/ndpi_main.c]: Better
